config/routes.rb
Rails.application.routes.draw do
  resources :blend_logs
  get 'blend_log/create'
  get 'blend_log/show'
  get 'blend_log/update'
  get 'blend_log/destroy'
  get 'blend_log/new'
  get 'blend_log/create'
  get 'blend_log/show'
  get 'blend_log/update'
  get 'blend_log/destroy'
  resources :blends


  get 'download_blends', to: 'blends#download_csv'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  get 'detailed_inventory', to: 'user_lots#detailed'

  delete 'logout', to: 'sessions#destroy'

  root to: 'main#index'
  get 'contact_us', to: 'main#contact_us'

  get 'coffee_market', to: 'markets#index'

  resources :users, only: [] do
    get 'lots_to_csv', to: 'user_lots#download_csv'
    get 'logs_to_csv', to: 'user_logs#download_csv'
    
    resources :lots, controller: 'user_lots' do
     
      patch 'mark_arrived', to: 'user_lots'
      get 'mark_removed', to: 'user_lots'
      patch 'edit', to: 'user_lots'
      patch 'update', to: 'user_lots'
    end
    resources :logs, controller: 'user_logs' do
      patch 'weight_out', to: 'user_logs'
      patch 'destroy', to: 'user_logs'
    end

    resources :current_products, controller: 'user_current_products' do
      
    end
    get 'completed_orders', to: 'user_order_requests#completed'
    get 'paid_orders', to: 'user_order_requests#paid'
    resources :order_requests, controller: 'user_order_requests' do
      
      patch 'mark_completed', to: 'user_order_requests'
      patch 'mark_paid', to: 'user_order_requests'
      delete 'delete', to: 'user_order_requests'
      resources :order_pieces, controller: 'user_order_pieces'
    end
  end
end

app/models/blend_log.rb
class BlendLog < ApplicationRecord
  belongs_to :blend
  belongs_to :log
end

app/controllers/blend_logs_controller.rb
class BlendLogsController < ApplicationController
  before_action :set_blend_log, only: %i[ show edit update destroy ]

  # GET /blend_logs or /blend_logs.json
  def index
    @blend_logs = BlendLog.all
  end

  # GET /blend_logs/1 or /blend_logs/1.json
  def show
  end

  # GET /blend_logs/new
  def new
    @blend_log = BlendLog.new
  end

  # GET /blend_logs/1/edit
  def edit
  end

  # POST /blend_logs or /blend_logs.json
  def create
    @blend_log = BlendLog.new(blend_log_params)

    respond_to do |format|
      if @blend_log.save
        format.html { redirect_to blend_log_url(@blend_log), notice: "Blend log was successfully created." }
        format.json { render :show, status: :created, location: @blend_log }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blend_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blend_logs/1 or /blend_logs/1.json
  def update
    respond_to do |format|
      if @blend_log.update(blend_log_params)
        format.html { redirect_to blend_log_url(@blend_log), notice: "Blend log was successfully updated." }
        format.json { render :show, status: :ok, location: @blend_log }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blend_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blend_logs/1 or /blend_logs/1.json
  def destroy
    @blend_log.destroy

    respond_to do |format|
      format.html { redirect_to blend_logs_url, notice: "Blend log was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blend_log
      @blend_log = BlendLog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blend_log_params
      params.require(:blend_log).permit(:blend_id, :log_id)
    end
end

app/helpers/blend_log_helper.rb
module BlendLogHelper
end

app/helpers/blend_logs_helper.rb
module BlendLogsHelper
end

app/views/blend_logs/_form.html.erb
<%= form_with(model: blend_log, local: true) do |form| %>
  <% if blend_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blend_log.errors.count, "error") %> prohibited this blend_log from being saved:</h2>

      <ul>
      <% blend_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :blend_id %>
    <%= form.text_field :blend_id %>
  </div>

  <div class="field">
    <%= form.label :log_id %>
    <%= form.text_field :log_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blend_logs/edit.html.erb
<h1>Editing Blend Log</h1>

<%= render 'form', blend_log: @blend_log %>

<%= link_to 'Show', @blend_log %> |
<%= link_to 'Back', blend_logs_path %>

app/views/blend_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blend Logs</h1>

<table>
  <thead>
    <tr>
      <th>Blend</th>
      <th>Log</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blend_logs.each do |blend_log| %>
      <tr>
        <td><%= blend_log.blend %></td>
        <td><%= blend_log.log %></td>
        <td><%= link_to 'Show', blend_log %></td>
        <td><%= link_to 'Edit', edit_blend_log_path(blend_log) %></td>
        <td><%= link_to 'Destroy', blend_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blend Log', new_blend_log_path %>

app/views/blend_logs/new.html.erb
<h1>New Blend Log</h1>

<%= render 'form', blend_log: @blend_log %>

<%= link_to 'Back', blend_logs_path %>

app/views/blend_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Blend:</strong>
  <%= @blend_log.blend %>
</p>

<p>
  <strong>Log:</strong>
  <%= @blend_log.log %>
</p>

<%= link_to 'Edit', edit_blend_log_path(@blend_log) %> |
<%= link_to 'Back', blend_logs_path %>