config/routes.rb
Rails.application.routes.draw do
  resources :blend_logs
  get 'blend_log/create'
  get 'blend_log/show'
  get 'blend_log/update'
  get 'blend_log/destroy'
  get 'blend_log/new'
  get 'blend_log/create'
  get 'blend_log/show'
  get 'blend_log/update'
  get 'blend_log/destroy'
  resources :blends


  get 'download_blends', to: 'blends#download_csv'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  get 'detailed_inventory', to: 'user_lots#detailed'

  delete 'logout', to: 'sessions#destroy'

  root to: 'main#index'
  get 'contact_us', to: 'main#contact_us'

  get 'coffee_market', to: 'markets#index'

  resources :users, only: [] do
    get 'lots_to_csv', to: 'user_lots#download_csv'
    get 'logs_to_csv', to: 'user_logs#download_csv'
    
    resources :lots, controller: 'user_lots' do
     
      patch 'mark_arrived', to: 'user_lots'
      get 'mark_removed', to: 'user_lots'
      patch 'edit', to: 'user_lots'
      patch 'update', to: 'user_lots'
    end
    resources :logs, controller: 'user_logs' do
      patch 'weight_out', to: 'user_logs'
      patch 'destroy', to: 'user_logs'
    end

    resources :current_products, controller: 'user_current_products' do
      
    end
    get 'completed_orders', to: 'user_order_requests#completed'
    get 'paid_orders', to: 'user_order_requests#paid'
    resources :order_requests, controller: 'user_order_requests' do
      
      patch 'mark_completed', to: 'user_order_requests'
      patch 'mark_paid', to: 'user_order_requests'
      delete 'delete', to: 'user_order_requests'
      resources :order_pieces, controller: 'user_order_pieces'
    end
  end
end

app/controllers/user_order_requests_controller.rb
class UserOrderRequestsController < ApplicationController

    def index 
        @pending_order_requests = Current.user.order_requests.pending
    end

    def new
        @order_request = OrderRequest.new
    end


    def create
        
        @order_request = Current.user.order_requests.build(order_request_params)
        if @order_request.save
            redirect_to user_order_request_path(Current.user, @order_request)
        else
            render :new
        end
    end

    def show 
        @order_request = OrderRequest.find(params[:id])
        @order_piece = OrderPiece.new
    end

  def mark_completed    
    @order_request = OrderRequest.find(params[:order_request_id])
    @order_request.update(status: 1)
    redirect_to user_order_requests_path(Current.user)
    end

    def mark_paid 
        @order_request = OrderRequest.find(params[:order_request_id])
        @order_request.update(status: 2)
        redirect_to  user_completed_orders_path(Current.user)
    end

    def delete 
        @order_request = OrderRequest.find(params[:order_request_id])
        @order_request.destroy
        redirect_to user_order_requests_path(Current.user)
    end

    def completed
        @completed_order_requests = Current.user.order_requests.completed.reverse
    end

    def paid
        @paid_order_requests = Current.user.order_requests.paid.reverse
    end
  


    private

    def order_request_params
        params.require(:order_request).permit(:employee_name, :recipient_name, :reason, :need_by_date, :invoice_number)
    end
end

app/views/user_order_requests/completed.html.erb
<div class="d-flex align-items-center justify-content-center"></div>

<div class="card text-center">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link" aria-current="false" href=<%=user_order_requests_path(Current.user)%>>Order Requests</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" aria-current="true" href=<%=  user_completed_orders_path(Current.user) %>>Completed Requests</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" aria-current="false" href=<%=  user_paid_orders_path(Current.user) %>>Paid Requests</a>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <h4 class="card-title">Completed Order Requests</h4>
    

    <table class="table card-title">
      <thead>
        <tr>

          <th scope="col">Employee Name</th>
          <th scope="col">Recipient Name</th>
          <th scope="col">Reason</th>
          <th scope="col">Need By Date</th>
           <th scope="col">Invoice Number</th>
          <th scope="col">Actions</th>
           
          

        </tr>
      </thead>
       <tbody>
        <% @completed_order_requests.each do |order_request| %>
        
            <tr class="table-primary">
                      <td><%= order_request.employee_name %></td>
                      <td><%= order_request.recipient_name %></td>
                        <td><%= order_request.reason %></td>
                        <td><%= order_request.need_by_date %></td>
                        <td><%= order_request.invoice_number %></td>

                        <td>
                         <a class="btn btn-success" href="<%= user_order_request_mark_paid_path(Current.user, order_request.id)%>"  data-method="patch" role="button" >Mark Paid/Accounted</a>
                          <a class="btn btn" href="<%= user_order_request_path(Current.user, order_request.id)%>"  data-method="get" role="button" >Show</a>
                        </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>

              <a href=<%= new_user_order_request_path %> class="btn btn-primary">Add New Request</a>

            </div>
          </div>

app/views/user_order_requests/index.html.erb
<div class="d-flex align-items-center justify-content-center"></div>

<div class="card text-center">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link active" aria-current="true" href="#">Order Requests</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=<%=  user_completed_orders_path(Current.user) %>>Completed Requests</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" aria-current="false" href=<%=  user_paid_orders_path(Current.user) %>>Paid Requests</a>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <h4 class="card-title">Order Requests</h4>
    

    <table class="table card-title">
      <thead>
        <tr>

          <th scope="col">Employee Name</th>
          <th scope="col">Recipient Name</th>
          <th scope="col">Reason</th>
          <th scope="col">Need By Date</th>
          <th scope="col">Invoice Number</th>
          <th scope="col">Actions</th>
          

        </tr>
      </thead>
       <tbody>
        <% @pending_order_requests.each do |order_request| %>
        
            <tr class="table-primary">
                      <td><%= order_request.employee_name %></td>
                      <td><%= order_request.recipient_name %></td>
                        <td><%= order_request.reason %></td>
                        <td><%= order_request.need_by_date %></td>
                        <td><%= order_request.invoice_number %></td>

                        <td>
                        <a class="btn btn-danger" href="<%= user_order_request_delete_path(Current.user, order_request.id)%>"  data-method="delete" role="button" >Delete</a>
                          <a class="btn btn-success" href="<%= user_order_request_mark_completed_path(Current.user, order_request.id)%>"  data-method="patch" role="button" >Mark Completed</a>
                          <a class="btn btn" href="<%= user_order_request_path(Current.user, order_request.id)%>"  data-method="get" role="button" >Show</a>
                        </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>

              <a href=<%= new_user_order_request_path %> class="btn btn-primary">Add New Request</a>

            </div>
          </div>

app/views/user_order_requests/new.html.erb
<h1>Create Order Request</h1>

<%= form_with model: @order_request, url: user_order_requests_path, method: :post do |form| %>

<div class="mb-3">
  <%= form.label "Employee Name" %>
  <%= form.text_field :employee_name, class: "form-control" , placeholder: "Bryce Wein", required: true %>
</div>
<div class="mb-3">
  <%= form.label "Recipient Name" %>
  <%= form.text_field :recipient_name, class: "form-control" , placeholder: "Name/Buisness", required: true %>
</div>
<div class="mb-3">
  <%= form.label "Reason" %>
  <%= form.select :reason, ["Sample","Wholesale","Order For Friend", "PCC Event"], required: true %>
</div>
<div class="mb-3">
  <%= form.label "Need By Date" %>
  <%= form.date_field :need_by_date, class: "form-control" , required: true %>
</div>
<div class="mb-3">
  <%= form.label "Invoice Number" %>
  <%= form.text_field :invoice_number, class: "form-control" , required: false %>
</div>
<div class="mb-3">
  <%= form.submit class: "btn btn-primary" %>
</div>
<% end %>

app/views/user_order_requests/paid.html.erb
<div class="d-flex align-items-center justify-content-center"></div>

<div class="card text-center">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link" aria-current="false" href=<%=user_order_requests_path(Current.user)%>>Order Requests</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" aria-current="false" href=<%=  user_completed_orders_path(Current.user) %>>Completed Requests</a>
      </li>
       <li class="nav-item">
        <a class="nav-link active" aria-current="true" href=<%=  user_paid_orders_path(Current.user) %>>Paid Requests</a>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <h4 class="card-title">Paid Requests</h4>
    

    <table class="table card-title">
      <thead>
        <tr>

          <th scope="col">Employee Name</th>
          <th scope="col">Recipient Name</th>
          <th scope="col">Reason</th>
          <th scope="col">Need By Date</th>
           <th scope="col">Invoice Number</th>
          <th scope="col">Actions</th>
           
          

        </tr>
      </thead>
       <tbody>
        <% @paid_order_requests.each do |order_request| %>
        
            <tr class="table-primary">
                      <td><%= order_request.employee_name %></td>
                      <td><%= order_request.recipient_name %></td>
                        <td><%= order_request.reason %></td>
                        <td><%= order_request.need_by_date %></td>
                        <td><%= order_request.invoice_number %></td>

                        <td>
                          <a class="btn btn" href="<%= user_order_request_path(Current.user, order_request.id)%>"  data-method="get" role="button" >Show</a>
                        </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>

              

            </div>
          </div>

app/views/user_order_requests/show.html.erb
<div class="d-flex align-items-center justify-content-center"></div>

<div class="card text-center">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link" aria-current="true" href=<%=user_order_requests_path(Current.user)%>>Order Requests</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=<%=  user_completed_orders_path(Current.user) %>>Completed Requests</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" aria-current="false" href=<%= "#" %>>  <%=@order_request.recipient_name%></a>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <h1 class="card-title"> <%=@order_request.recipient_name%>  </h1>
    <h4 class="card-title"> <%=@order_request.employee_name%>  </h4>
    <h4 class="card-title"> <%=@order_request.reason%>  </h4>
    <h4 class="card-title"> <%=@order_request.need_by_date%>  </h4>

  
    

    <table class="table card-title">
      <thead>
        <tr>

          <th scope="col">Quantity</th>
          <th scope="col">Coffee Name</th>
          <th scope="col">Size</th>
          <th scope="col">Whole Bean / Ground</th>
           <% if @order_request.status == 0%>
          <th scope="col">Actions</th>
          <% end %>
          

        </tr>
      </thead>
       <tbody>
        <% @order_request.order_pieces.each do |piece| %>
        
            <tr class="table-primary">
                      <td><%= piece.quantity %></td>
                      <td><%= piece.coffee_name %></td>
                        <td><%= piece.size %></td>
                        <td><%= piece.ground %></td>
                        <% if @order_request.status == 0%>
                         <td>
                          <a class="btn btn-danger" href="<%= user_order_request_order_piece_path(Current.user, @order_request.id, piece.id)%>"  data-method="delete" role="button" >Delete</a>
                        </td>
                        <% end %>

            
                    </tr>
                  <% end %>
                </tbody>
              </table>
<% if @order_request.status == 0%>
          <h3>Add Order Piece</h3>

<%= form_with model: @order_piece, url: user_order_request_order_pieces_path(Current.user, @order_request.id), method: :post do |form| %>

<div class="mb-3">
  <%= form.label "Product Name:" %>
  <%= form.select :coffee_name, Current.user.current_products.names, required: true %>
</div>
<div class="mb-3">
  <%= form.label "Size:" %>
  <%= form.select :size, ["60g", "4oz", "12oz", "2LB", "5LB", "Small", "Medium", "Large", "XLarge", "XXLarge"], required: true %>
</div>
<div class="mb-3">
  <%= form.label "Quantity:" %>
  <%= form.select :quantity, [1,2,3,4,5,6,7,8,9,10], required: true %>
</div>
<div class="mb-3">
  <%= form.label "Whole Bean or Ground?" %>
  <%= form.select :ground, ["Whole Bean", "Course Ground", "Medium Ground", "Fine Ground", "N/A"], required: true %>
</div>
<div class="mb-3">
  <%= form.submit class: "btn btn-primary" %>
</div>


<%end%>

<% end %>


            </div>
          </div>


       