config/routes.rb
Rails.application.routes.draw do
  resources :blend_logs
  get 'blend_log/create'
  get 'blend_log/show'
  get 'blend_log/update'
  get 'blend_log/destroy'
  get 'blend_log/new'
  get 'blend_log/create'
  get 'blend_log/show'
  get 'blend_log/update'
  get 'blend_log/destroy'
  resources :blends


  get 'download_blends', to: 'blends#download_csv'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  get 'detailed_inventory', to: 'user_lots#detailed'

  delete 'logout', to: 'sessions#destroy'

  root to: 'main#index'
  get 'contact_us', to: 'main#contact_us'

  get 'coffee_market', to: 'markets#index'

  resources :users, only: [] do
    get 'lots_to_csv', to: 'user_lots#download_csv'
    get 'logs_to_csv', to: 'user_logs#download_csv'
    
    resources :lots, controller: 'user_lots' do
     
      patch 'mark_arrived', to: 'user_lots'
      get 'mark_removed', to: 'user_lots'
      patch 'edit', to: 'user_lots'
      patch 'update', to: 'user_lots'
    end
    resources :logs, controller: 'user_logs' do
      patch 'weight_out', to: 'user_logs'
      patch 'destroy', to: 'user_logs'
    end

    resources :current_products, controller: 'user_current_products' do
      
    end
    get 'completed_orders', to: 'user_order_requests#completed'
    get 'paid_orders', to: 'user_order_requests#paid'
    resources :order_requests, controller: 'user_order_requests' do
      
      patch 'mark_completed', to: 'user_order_requests'
      patch 'mark_paid', to: 'user_order_requests'
      delete 'delete', to: 'user_order_requests'
      resources :order_pieces, controller: 'user_order_pieces'
    end
  end
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>

  <div class=" alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class=" alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Cloud Coffee</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <% if Current.user %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href=<%= user_lots_path(Current.user) %>>Green Coffee</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href=<%= user_logs_path(Current.user) %>>Roast Log</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href=<%= blends_path %>>Blend Log</a>
          </li>
          
          
        <% end %>
      </ul>
      <ul class='navbar-nav ms-auto mb-2 mb-lg-0'>
        <% if Current.user %>
          <li class="nav-item">
            <span class="navbar-text"><%= Current.user.email %></span>
          </li>
          <li class="nav-item">
            <%= button_to "Contact Us", contact_us_path, method: :get, class: "btn btn-outline-secondary"%>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", sign_in_path, class: 'nav-link' %>
          </li>
        <%end %>

      </ul>

    </div>
  </div>
</nav>

<br>
<br>