config/routes.rb
Rails.application.routes.draw do
  resources :blend_logs
  get 'blend_log/create'
  get 'blend_log/show'
  get 'blend_log/update'
  get 'blend_log/destroy'
  get 'blend_log/new'
  get 'blend_log/create'
  get 'blend_log/show'
  get 'blend_log/update'
  get 'blend_log/destroy'
  resources :blends


  get 'download_blends', to: 'blends#download_csv'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  get 'detailed_inventory', to: 'user_lots#detailed'

  delete 'logout', to: 'sessions#destroy'

  root to: 'main#index'
  get 'contact_us', to: 'main#contact_us'

  get 'coffee_market', to: 'markets#index'

  resources :users, only: [] do
    get 'lots_to_csv', to: 'user_lots#download_csv'
    get 'logs_to_csv', to: 'user_logs#download_csv'
    
    resources :lots, controller: 'user_lots' do
     
      patch 'mark_arrived', to: 'user_lots'
      get 'mark_removed', to: 'user_lots'
      patch 'edit', to: 'user_lots'
      patch 'update', to: 'user_lots'
    end
    resources :logs, controller: 'user_logs' do
      patch 'weight_out', to: 'user_logs'
      patch 'destroy', to: 'user_logs'
    end

    resources :current_products, controller: 'user_current_products' do
      
    end
    get 'completed_orders', to: 'user_order_requests#completed'
    get 'paid_orders', to: 'user_order_requests#paid'
    resources :order_requests, controller: 'user_order_requests' do
      
      patch 'mark_completed', to: 'user_order_requests'
      patch 'mark_paid', to: 'user_order_requests'
      delete 'delete', to: 'user_order_requests'
      resources :order_pieces, controller: 'user_order_pieces'
    end
  end
end

app/controllers/user_lots_controller.rb
class UserLotsController < ApplicationController
  def index; end

  def new
    @lot = Lot.new
  end

  def create
    lot = Lot.new(lot_params)
    lot.current_amount = lot_params[:kg_received]
    lot.user_id = Current.user.id
    lot.status = 1
    if lot.save
      redirect_to user_lots_path(Current.user)
    else
      render :new
    end
  end

  def mark_arrived
    lot = Lot.find(params[:lot_id])
    lot.status = 2
    lot.save
    redirect_to user_lots_path
  end

  def mark_removed
    lot = Lot.find(params[:lot_id])
    lot.status = 3
    lot.save
    redirect_to user_lots_path
  end

  def detailed
    @inventory = Current.user.lots
  end

  def edit 
   @lot = Lot.find(params[:id])
  end

  def update 
    lot = Lot.find(params[:lot_id])
    lot.update(lot_params)
    redirect_to user_lots_path
  end

  # download csv from User.lots
  def download_csv
    @lots = Current.user.lots
    respond_to do |format|
      format.html
      format.csv { send_data @lots.to_csv, filename: "lots-#{Date.today}.csv" }
    end
  end
  

  private

  def lot_params
    params.require(:lot).permit(:name, :sku, :importer, :description, :us_arrival, :price_per, :sample_roasted_date,
                                :density, :moisture, :bean_size, :item_size, :quantity_recieved, :kg_received, :invoice_number, :pcc_id, :ico)
  end
end

app/views/user_lots/detailed.html.erb
<div class="d-flex align-items-center justify-content-center"></div>

<div class="card text-center">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link " href=<%= user_lots_path(Current.user) %>>Inventory</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" aria-current="true" href="#">Detailed Inventory</a>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <h4 class="card-title">Current Inventory</h4>

    <table class="table card-title">
      <thead>
        <tr>

          <th scope="col">Name</th>
          <th scope="col">PCC ID</th>
          <th scope="col">SKU</th>
          <th scope="col">ICO</th>
          <th scope="col">Importer</th>
          <th scope="col">Description</th>
          <th scope="col">Price Per Lb</th>
          <th scope="col">US Arrival</th>
          <th scope="col">Unit Size</th>
          <th scope="col">Quantity Reveived</th>
          <th scope="col">Kg Received</th>
          <th scope="col">Invoice Number</th>
          <th scope="col">Added Date</th>

        </tr>
      </thead>
      <tbody>
        <% @inventory.each do |lot| %>
          <tr>
            <td><%= lot.name %></td>
            <td><%= lot.pcc_id %></td>
            <td><%= lot.sku %></td>
            <td><%= lot.ico %></td>
            <td><%= lot.importer %></td>
            <td><%= lot.description %></td>
            <td><%= lot.price_per %></td>
            <td><%= lot.us_arrival %></td>
            <td><%= lot.item_size %></td>
            <td><%= lot.quantity_recieved %></td>
            <td><%= lot.kg_received %></td>
            <td><%= lot.invoice_number %></td>
            <td><%= lot.created_at %></td>

          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/user_lots/edit.html.erb
<h1>Edit <%= @lot.name %> </h1>

<%= form_with model: @lot, url: user_lot_update_path(Current.user, @lot.id), method: :patch do |form| %>

<div class="mb-3">
  <%= form.label :name %>
  <%= form.text_field :name, class: "form-control" , placeholder: "Guatamala", required: true %>
</div>
<div class="mb-3">
  <%= form.label "Pcc Id" %>
  <%= form.text_field :pcc_id, class: "form-control" , placeholder: "ETH2", required: true %>
</div>
<div class="mb-3">
  <%= form.label "ICO" %>
  <%= form.text_field :ico, class: "form-control" , placeholder: "002/1643/0259"%>
</div>
<div class="mb-3">
  <%= form.label :sku %>
  <%= form.text_field :sku , class: "form-control", placeholder: "GEN22BREC"%>
</div>
<div class="mb-3">
  <%= form.label :importer %>
  <%= form.text_field :importer , class: "form-control", placeholder: "Genuine Origin"%>
</div>
<div class="mb-3">
  <%= form.label :description %>
  <%= form.text_field :description , class: "form-control", placeholder: "Washed, Excelso"%>
</div>
<div class="mb-3">
  <%= form.label "US Arrival Date" %>
  <%= form.date_field :us_arrival , class: "form-control"%>
</div>
<div class="mb-3">
  <%= form.label "Price Per Lb" %>
  <%= form.number_field :price_per , class: "form-control", placeholder: "4.87",in: 1.0..500.0, step: 0.01%>
</div>
<div class="mb-3">
  <%= form.label "Sample Roast Date" %>
  <%= form.date_field :sample_roasted_date , class: "form-control"%>
</div>
<div class="mb-3">
  <%= form.label "Density g/L" %>
  <%= form.number_field :density , class: "form-control", placeholder: "675",in: 1.0..1000.0, step: 0.01%>
</div>
<div class="mb-3">
  <%= form.label "Moisture Percentage" %>
  <%= form.number_field :moisture , class: "form-control", placeholder: "12.40",in: 1.0..100.0, step: 0.01%>
</div>
<div class="mb-3">
  <%= form.label "Bean Size" %>
  <%= form.text_field :bean_size , class: "form-control", placeholder: "17/18"%>
</div>
<div class="mb-3">
  <%= form.label "Item size" %>
  <%= form.text_field :item_size , class: "form-control", placeholder: "65kg", required: true %>
</div>
<div class="mb-3">
  <%= form.label "Number of units received" %>
  <%= form.number_field :quantity_recieved , class: "form-control", placeholder: "1",in: 1.0..20.0, step: 0.01, required: true %>
</div>
<div class="mb-3">
  <%= form.label "Kg Received" %>
  <%= form.number_field :kg_received , class: "form-control", placeholder: "1",in: 1.0..1000, step: 0.01, required: true %>
</div>
<div class="mb-3">
  <%= form.label "invoice_number" %>
  <%= form.text_field :invoice_number , class: "form-control", placeholder: "SO179209"%>
</div>
<div class="mb-3">
  <%= form.submit class: "btn btn-primary" %>

</div>
<% end %>

app/views/user_lots/index.html.erb
<div class="d-flex align-items-center justify-content-center"></div>


<div class="card text-center">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link active" aria-current="true" href="#">Inventory</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=<%= detailed_inventory_path %>>Detailed Inventory</a>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <h4 class="card-title">Current Inventory</h4>
    
    <a href=<%= "/users/#{Current.user.id}>/lots_to_csv.csv" %> class="btn btn-secondary">Download Green Coffee Records</a>

    <table class="table card-title">
      <thead>
        <tr>

          <th scope="col">Name</th>
          <th scope="col">PCC ID</th>
          <th scope="col">Current Quantity (Kg)</th>
          <th scope="col">Action</th>
         

        </tr>
      </thead>
      <tbody>
        <% Current.user.lots.ordered_or_arrived_lots.each do |lot| %>
          <% if lot.status == 1 %>
            <tr class="table-primary">
              <% elsif lot.current_amount < 25  %>
                <tr class="table-danger">
                  <% elsif lot.current_amount < 40 %>
                    <tr class="table-warning">
                    <% else %>
                      <tr class="table-success">
                      <% end %>
                      <td><%= lot.name %></td>
                      <td><%= lot.pcc_id %></td>
                      <td><%= lot.current_amount %></td>
                      <% if lot.status == 1 %>
                        <td><%= button_to "Mark Arrived", user_lot_mark_arrived_path(Current.user, lot), method: :patch%></td>
                      <% else %>

                        <td>
                        

                          <a class="btn btn-primary" href="<%= edit_user_lot_path(Current.user, lot.id)%>" role="button">Edit</a>
                           <a class="btn btn-danger" href="<%= user_lot_mark_removed_path(Current.user, lot)%>" role="button">Remove</a>
                          
                        </td>

                       
                      <% end %>
                    </tr>
                  <% end %>
                </tbody>
              </table>

              <a href=<%= new_user_lot_path %> class="btn btn-primary">Add New Lot</a>


 

            </div>
          </div>

app/views/user_lots/new.html.erb
<h1>Add New Lot To Inventory</h1>

<%= form_with model: @lot, url: user_lots_path, method: :post do |form| %>

<div class="mb-3">
  <%= form.label :name %>
  <%= form.text_field :name, class: "form-control" , placeholder: "Guatamala", required: true %>
</div>
<div class="mb-3">
  <%= form.label "Id" %>
  <%= form.text_field :pcc_id, class: "form-control" , placeholder: "ETH2", required: true %>
</div>
<div class="mb-3">
  <%= form.label "ICO" %>
  <%= form.text_field :ico, class: "form-control" , placeholder: "002/1643/0259"%>
</div>
<div class="mb-3">
  <%= form.label :sku %>
  <%= form.text_field :sku , class: "form-control", placeholder: "GEN22BREC"%>
</div>
<div class="mb-3">
  <%= form.label :importer %>
  <%= form.text_field :importer , class: "form-control", placeholder: "Genuine Origin"%>
</div>
<div class="mb-3">
  <%= form.label :description %>
  <%= form.text_field :description , class: "form-control", placeholder: "Washed, Excelso"%>
</div>
<div class="mb-3">
  <%= form.label "US Arrival Date" %>
  <%= form.date_field :us_arrival , class: "form-control"%>
</div>
<div class="mb-3">
  <%= form.label "Price Per Lb" %>
  <%= form.number_field :price_per , class: "form-control", placeholder: "4.87",in: 1.0..500.0, step: 0.01%>
</div>
<div class="mb-3">
  <%= form.label "Sample Roast Date" %>
  <%= form.date_field :sample_roasted_date , class: "form-control"%>
</div>
<div class="mb-3">
  <%= form.label "Density g/L" %>
  <%= form.number_field :density , class: "form-control", placeholder: "675",in: 1.0..1000.0, step: 0.01%>
</div>
<div class="mb-3">
  <%= form.label "Moisture Percentage" %>
  <%= form.number_field :moisture , class: "form-control", placeholder: "12.40",in: 1.0..100.0, step: 0.01%>
</div>
<div class="mb-3">
  <%= form.label "Bean Size" %>
  <%= form.text_field :bean_size , class: "form-control", placeholder: "17/18"%>
</div>
<div class="mb-3">
  <%= form.label "Item size" %>
  <%= form.text_field :item_size , class: "form-control", placeholder: "65kg", required: true %>
</div>
<div class="mb-3">
  <%= form.label "Number of units received" %>
  <%= form.number_field :quantity_recieved , class: "form-control", placeholder: "1",in: 1.0..20.0, step: 0.01, required: true %>
</div>
<div class="mb-3">
  <%= form.label "Kg Received" %>
  <%= form.number_field :kg_received , class: "form-control", placeholder: "1",in: 1.0..1000, step: 0.01, required: true %>
</div>
<div class="mb-3">
  <%= form.label "invoice_number" %>
  <%= form.text_field :invoice_number , class: "form-control", placeholder: "SO179209"%>
</div>
<div class="mb-3">
  <%= form.submit class: "btn btn-primary" %>

</div>
<% end %>